logo: /images/svdb.png
han_type: zh-Hant
menu:
  首页: /
  归档: /pigeonhole
  链接: /links
  关于: /about
disqus:
  short_name: mqjing
icon:
  rss: /atom.xml
  facebook: YOUR_FACEBOOK_ID
  twitter: YOUR_TWITTER_ID
  github: mqjing
  weibo: YOUR_WEIBO_ID
favicon: /images/favicon.ico